/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface MtHeading {
        "color": string;
        "type": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
    }
}
declare global {
    interface HTMLMtHeadingElement extends Components.MtHeading, HTMLStencilElement {
    }
    var HTMLMtHeadingElement: {
        prototype: HTMLMtHeadingElement;
        new (): HTMLMtHeadingElement;
    };
    interface HTMLElementTagNameMap {
        "mt-heading": HTMLMtHeadingElement;
    }
}
declare namespace LocalJSX {
    interface MtHeading {
        "color"?: string;
        "type"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
    }
    interface IntrinsicElements {
        "mt-heading": MtHeading;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mt-heading": LocalJSX.MtHeading & JSXBase.HTMLAttributes<HTMLMtHeadingElement>;
        }
    }
}
